### ISSUE TITLE
New Firebase Segment on Oh My Posh!

### ISSUE THREAD

**Issue by ivan-the-terrible** [QuentinPhrl/omp-firebase-prompt#1]
Thanks for suggesting this!
I decided to take you up on this functionality and add this as a legitimate segment on Oh My Posh:
https://github.com/JanDeDobbeleer/oh-my-posh/pull/4840

It was just merged in and is live! https://ohmyposh.dev/docs/segments/firebase

Since you're actively using this functionality, give the new segment a try and let me know if there are any bugs!
Thanks for your suggestion and I hope the new segment helps!

Take care,

\- Ivan

**Comment by QuentinPhrl** [comment]
Hi

Thank you so much for doing the dirty work 😜 

However it doesn't work exactly like the script I originally made, because if you are in a child folder of the active firebase project the segment doesn't display. 

I'll close this issue and open one on the official repo with more information. 

Thanks again for adding this segment, which I think will be useful to many people.

**Comment by ivan-the-terrible** [comment]
Ah! Good catch. I'll put out a patch to check if the current path is **_part_** of the active project path
